version: '3.8'
services:
  nexus:
    image: ghcr.io/andreitere/mysql_db_backup:${VERSION:-latest}
    build: .
    container_name: ${APP_NAME:-mysql_database_backup}-mysql-backup
    volumes:
      - "db_backup:/backups"
    environment:
      - TG_BOT_TOKEN=${TG_BOT_TOKEN}
      - TG_CHAT_ID=${TG_CHAT_ID}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQLSWORD}
      - MYSQL_DB=${MYSQLES_DB}
      - MYSQL_HOST=${MYSQL_HOST}
      - APP_NAME=${APP_NAME}
      - CRON_SCHEDULE=${CRON_SCHEDULE}
    deploy:
      resources:
        limits:
          memory: "1g"
volumes:
  db_backup:
    external: true
