version: '3.8'
services:
  nexus:
    image: mysql_backup
    build: .
    container_name: ${APP_NAME:-mysql_database_backup}-mysql-backup
    volumes:
      - "db_backup:/backups"
volumes:
  db_backup:
    external: true
